# Generated by Django 3.2 on 2023-12-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20231218_2308'),
        ('reviews', '0004_alter_comment_options'),
    ]

    operations = [
    ]
